
services:
  go-app:
    build: .
    restart: always
    ports:
      - "9004:8080"
    volumes:
      - ./secret:/secret
    env_file:
      - .env
    networks:
      - shared-db

networks:
  shared-db:
    external: true
    name: shared-db
