
services:
  go-app:
    build: .
    restart: always
    ports:
      - "9004:8080"
    volumes:
      - ./secret:/secret
      - ./secret/database.pem:/secret
    env_file:
      - .env

networks:
  default:
    driver: bridge
